### ISSUE TITLE
Response code is 202 on successful /api/push request, getting caught as error

### ISSUE THREAD

**Issue by ghost** [cojohn/node-urban-airship#12]
Line 186 is where the error gets created
Line 172 is where you check for status codes. Seems like 202 should be included in that array, to avoid returning an error when a successful push has occurred.

**Comment by cojohn** [comment]
Not sure which version of the library you're using, but the current version accepts response codes from the array `[200,201,202,204]` on line 164 of `lib/urban-airship.js` in `_transport()`. Can you post your error log?
