### ISSUE TITLE
Please consider supplying a License file

### ISSUE THREAD

**Issue by kgambrel** [cojohn/node-urban-airship#5]
Hi,

I work for a large company.  I'm interested in using node-urban-airship, for an internal project.   However, the company won't even allow an evaluation to occur without some kind of license identifying who the copyright belongs to and a statement about licensing (GPL, MIT, BSD, Apache, whatever).

Please consider at least putting a LICENSE file in the root directory, and potentially adding copyright statements in the headers for each source file.

Thanks, 

Kevin Gambrel
Technology Manager
Walt Disney Animation Studios
kevin.p.gambrel@disneyanimation.com

**Comment by cojohn** [comment]
I'll add this in the next day or so, probably MIT unless that's objectionable.

**Comment by truongvo** [comment]
+1...thank you!

**Comment by kgambrel** [comment]
MIT is perfectly fine.  Thanks for the quick response.
-kg

**Comment by cojohn** [comment]
I've added a license file and attached the license to the readme. If a copyright notice is desired/needed in the source files, please let me know. Cheers!
